# Generated by Django 3.2 on 2021-06-26 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_reponsibility',
            new_name='job_responsibility',
        ),
    ]
