-- 总用户数：4372
-- SELECT COUNT(DISTINCT CUSTOMERID) FROM OnlineRetail;
-- 每个用户的消费总金额、消费总订单数
-- SELECT CUSTOMERID,ROUND(SUM(UNITPRICE * QUANTITY),2),
-- COUNT(DISTINCT INVOICENO) 
-- FROM OnlineRetail GROUP BY CUSTOMERID 
-- ORDER BY SUM(UNITPRICE * QUANTITY) DESC;
-- 判断质量较高的300个用户他们的总消费金额/总消费金额(20%的用户贡献了80%销售额)
-- SELECT SUM(QUANTITY * UnitPrice) AS 总销售额 FROM OnlineRetail;

SELECT SUM(SALES)/9747747.93 AS 头部用户消费金额占比,
COUNT(CUSTOMERID)/4372 AS 头部用户数占比,
SUM(SALES)/COUNT(CUSTOMERID) AS 客单价
FROM 
(SELECT CUSTOMERID,ROUND(SUM(UNITPRICE * QUANTITY),2) AS SALES,
COUNT(DISTINCT INVOICENO) 
FROM OnlineRetail WHERE CUSTOMERID IS NOT NULL
GROUP BY CUSTOMERID 
ORDER BY SUM(UNITPRICE * QUANTITY) DESC LIMIT 874) T1;

-- 判断质量较低的xxx个用户他们的总消费金额/总消费金额(80%的用户贡献了20%销售额)
SELECT SUM(SALES)/9747747.93 AS 头部用户消费金额占比,
COUNT(CUSTOMERID)/4372 AS 头部用户数占比,
SUM(SALES)/COUNT(CUSTOMERID) AS 客单价
FROM 
(SELECT CUSTOMERID,ROUND(SUM(UNITPRICE * QUANTITY),2) AS SALES,
COUNT(DISTINCT INVOICENO) 
FROM OnlineRetail WHERE CUSTOMERID IS NOT NULL
GROUP BY CUSTOMERID HAVING SUM(UNITPRICE * QUANTITY)>0
ORDER BY SUM(UNITPRICE * QUANTITY) LIMIT 3498) T1;