# Generated by Django 2.2.4 on 2019-08-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190824_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish_data',
            new_name='publish_date',
        ),
    ]
