-- 首先，可以获取每个月的用户id列表

-- SELECT CUSTOMERID,DATE_FORMAT(INVOICEDATE,'%Y-%m') FROM OnlineRetail 
-- GROUP BY DATE_FORMAT(INVOICEDATE,'%Y-%m'),customerid;

-- 接着，可以循环比较当前月和下个月，每个用户id是否重复出现过
-- SELECT COUNT(B.M2) / COUNT(*) FROM
-- (SELECT CUSTOMERID,DATE_FORMAT(INVOICEDATE,'%Y-%m') as m1 FROM OnlineRetail 
-- WHERE DATE_FORMAT(INVOICEDATE,'%Y-%m') = '2011-01'
-- GROUP BY DATE_FORMAT(INVOICEDATE,'%Y-%m'),customerid) A 
-- LEFT JOIN
-- (SELECT CUSTOMERID,DATE_FORMAT(INVOICEDATE,'%Y-%m') as m2 FROM OnlineRetail 
-- WHERE DATE_FORMAT(INVOICEDATE,'%Y-%m') = '2011-02'
-- GROUP BY DATE_FORMAT(INVOICEDATE,'%Y-%m'),customerid) B 
-- ON A.CUSTOMERID = B.CUSTOMERID;

-- 最后，统计有回购行为的用户id，再除以总户数，就能得到~了吧
-- SELECT m1,COUNT(m1),COUNT(m2) FROM
-- (SELECT CUSTOMERID,DATE_FORMAT(INVOICEDATE,'%Y-%m') as m1 FROM OnlineRetail 
-- -- WHERE DATE_FORMAT(INVOICEDATE,'%Y-%m') = '2011-01'
-- GROUP BY DATE_FORMAT(INVOICEDATE,'%Y-%m'),customerid) A 
-- LEFT JOIN
-- (SELECT CUSTOMERID,DATE_FORMAT(INVOICEDATE,'%Y-%m') as m2 FROM OnlineRetail 
-- -- WHERE DATE_FORMAT(INVOICEDATE,'%Y-%m') = '2011-02'
-- GROUP BY DATE_FORMAT(INVOICEDATE,'%Y-%m'),customerid) B 
-- ON A.CUSTOMERID = B.CUSTOMERID
-- AND m1 = DATE_SUB(m2,INTERVAL 1 MONTH)
-- GROUP BY m1,m2;

-- test
SELECT DATE_FORMAT(m1,'%Y-%m'),COUNT(m1),COUNT(m2),COUNT(m2)/COUNT(m1) FROM
(SELECT CUSTOMERID,DATE_FORMAT(INVOICEDATE,'%Y-%m-01') as m1 FROM OnlineRetail 
-- WHERE DATE_FORMAT(INVOICEDATE,'%Y-%m') = '2011-01'
GROUP BY DATE_FORMAT(INVOICEDATE,'%Y-%m-01'),customerid) A 
LEFT JOIN
(SELECT CUSTOMERID,DATE_FORMAT(INVOICEDATE,'%Y-%m-01') as m2 FROM OnlineRetail 
-- WHERE DATE_FORMAT(INVOICEDATE,'%Y-%m') = '2011-02'
GROUP BY DATE_FORMAT(INVOICEDATE,'%Y-%m-01'),customerid) B 
ON A.CUSTOMERID = B.CUSTOMERID
AND m1 = DATE_SUB(m2,INTERVAL 1 MONTH)
GROUP BY m1;