-- 总用户数：4372
-- SELECT COUNT(DISTINCT CUSTOMERID) FROM OnlineRetail;
-- 每个用户的消费总金额、消费总订单数
-- SELECT CUSTOMERID,ROUND(SUM(UNITPRICE * QUANTITY),2),
-- COUNT(DISTINCT INVOICENO) 
-- FROM OnlineRetail GROUP BY CUSTOMERID 
-- ORDER BY SUM(UNITPRICE * QUANTITY) DESC;
-- 判断质量较高的300个用户他们的总消费金额/总消费金额(20%的用户贡献了80%销售额)
SELECT SUM(IF(UnitPrice>0,UnitPrice,0)*QUANTITY) AS 消费额,
COUNT(DISTINCT CUSTOMERID) as 用户数
FROM OnlineRetail;

SELECT 
SUM(SALES)/9769872 AS '消费占比',
COUNT(us)/4372 AS '用户占比',
SUM(SALES)/COUNT(us) AS '客单价' FROM
(SELECT CUSTOMERID AS us,ROUND(SUM(UNITPRICE * QUANTITY),2) AS SALES
FROM OnlineRetail WHERE CustomerID IS NOT NULL 
GROUP BY CUSTOMERID 
ORDER BY SUM(UNITPRICE * QUANTITY) DESC LIMIT 874) T1;
-- 判断质量较低的xxx个用户他们的总消费金额/总消费金额(80%的用户贡献了20%销售额)SELECT 
SELECT SUM(SALES)/9769872 AS '消费占比',
COUNT(us)/4372 AS '用户占比',
SUM(SALES)/COUNT(us) AS '客单价' FROM
(SELECT CUSTOMERID AS us,ROUND(SUM(UNITPRICE * QUANTITY),2) AS SALES
FROM OnlineRetail WHERE CustomerID IS NOT NULL
AND QUANTITY>0
GROUP BY CUSTOMERID 
ORDER BY SUM(UNITPRICE * QUANTITY) LIMIT 3000) T1;
