# Generated by Django 2.1.7 on 2019-05-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSPModels',
            fields=[
                ('sspid', models.AutoField(primary_key=True, serialize=False)),
                ('xmpzh', models.CharField(max_length=50)),
                ('xmlb', models.CharField(max_length=20)),
                ('xkfl', models.CharField(max_length=20)),
                ('xmmc', models.CharField(max_length=200)),
                ('lxsj', models.DateField()),
            ],
        ),
    ]
